import { describe, it, expect } from "vitest";
import {
  buildColumnHeaderTooltipLines,
  describeAutoGeneratedColumn,
} from "../components/table/tableDataColumnHints";

describe("describeAutoGeneratedColumn", () => {
  it("MySQL auto_increment → 「自增」", () => {
    expect(describeAutoGeneratedColumn("auto_increment")).toBe("自增");
  });

  it("PostgreSQL identity 列 → 「自动生成」", () => {
    expect(describeAutoGeneratedColumn("identity")).toBe("自动生成");
  });

  it("PostgreSQL always generated 列 → 「自动生成」", () => {
    expect(describeAutoGeneratedColumn("always generated")).toBe("自动生成");
  });

  it("PostgreSQL by default generated → 「自动生成」", () => {
    expect(describeAutoGeneratedColumn("by default generated")).toBe(
      "自动生成"
    );
  });

  it("identity + generated 组合（同时具备）也识别为自动生成", () => {
    expect(describeAutoGeneratedColumn("identity always generated")).toBe(
      "自动生成"
    );
  });

  it("大小写无关识别", () => {
    expect(describeAutoGeneratedColumn("IDENTITY")).toBe("自动生成");
    expect(describeAutoGeneratedColumn("AUTO_INCREMENT")).toBe("自增");
  });

  it("空值/未知 extra 视为普通列", () => {
    expect(describeAutoGeneratedColumn("")).toBeNull();
    expect(describeAutoGeneratedColumn("  ")).toBeNull();
    expect(describeAutoGeneratedColumn(null)).toBeNull();
    expect(describeAutoGeneratedColumn(undefined)).toBeNull();
    expect(describeAutoGeneratedColumn("on update CURRENT_TIMESTAMP")).toBeNull();
  });
});

describe("buildColumnHeaderTooltipLines", () => {
  it("显示数据库原始字段类型和字段注释", () => {
    expect(
      buildColumnHeaderTooltipLines("varchar(255)", "用户名称")
    ).toEqual(["类型：varchar(255)", "注释：用户名称"]);
  });

  it("没有注释时只显示数据库原始字段类型", () => {
    expect(buildColumnHeaderTooltipLines("bigint unsigned", "")).toEqual([
      "类型：bigint unsigned",
    ]);
  });
});
