/**
 * 根据列的 `extra` 字段判断是否为「自动生成」列，并返回中文短标签用于 UI 提示。
 *
 * 兼容数据库类型：
 * - MySQL：`auto_increment`
 * - PostgreSQL：`identity`、`always generated`、`by default generated`
 *   （由后端 `get_table_structure` 从 `information_schema.columns.is_identity` /
 *   `is_generated` 拼装而成）
 *
 * 返回 null 表示该列不是自动生成列，UI 应当作普通可输入列处理。
 */
export function describeAutoGeneratedColumn(
  extra: string | undefined | null
): string | null {
  const normalized = (extra ?? "").trim().toLowerCase();
  if (!normalized) return null;
  if (normalized === "auto_increment") return "自增";
  // 「identity」「always generated」「by default generated」均归为「自动生成」
  // 仅做包含判断，便于未来后端微调 extra 字面值（如增加 "stored generated" 等）时无需同步前端。
  if (normalized.includes("identity") || normalized.includes("generated")) {
    return "自动生成";
  }
  return null;
}
