import {
  useEffect,
  useState,
  useCallback,
  useRef,
  useMemo,
  useLayoutEffect,
  type MouseEvent as ReactMouseEvent,
} from "react";
import {
  Table,
  Button,
  Space,
  Typography,
  Alert,
  Modal,
  Form,
  Popconfirm,
  Badge,
  message,
  Tooltip,
  Checkbox,
  Popover,
  InputNumber,
  Pagination,
  Tag,
} from "antd";
import { SafeInput } from "../common/SafeInput";
import {
  ReloadOutlined,
  PlusOutlined,
  DeleteOutlined,
  ClockCircleOutlined,
  ConsoleSqlOutlined,
  ApiOutlined,
  ScissorOutlined,
  CheckOutlined,
  UndoOutlined,
  SettingOutlined,
  FileExcelOutlined,
  CopyOutlined,
  FilterOutlined,
  CodeOutlined,
  CalculatorOutlined,
  ArrowUpOutlined,
  ArrowDownOutlined,
} from "@ant-design/icons";
import type { ColumnsType, ColumnType } from "antd/es/table";
import { useShallow } from "zustand/react/shallow";
import {
  useTableDataStore,
  type PendingChange,
} from "../../stores/tableDataStore";
import { useDatabaseStore } from "../../stores/databaseStore";
import { useConnectionStore } from "../../stores/connectionStore";
import {
  useTableColumnSettingsStore,
  type TableColumnSettings,
} from "../../stores/tableColumnSettingsStore";
import { useClientReadOnly } from "../../hooks/useClientReadOnly";
import {
  generateInsertStatements,
  generateUpdateStatements,
  rowsToJsonArrayString,
} from "../../utils/sqlUtils";
import { queryFullRows } from "../../services/tauriCommands";
import { copyTextWithBreadcrumb } from "../../utils/crashBreadcrumbs";
import { WhereFilterBuilder } from "./WhereFilterBuilder";
import {
  type WhereFilterConfig,
  isStringColumnType,
} from "../../utils/whereFilterUtils";
import { VirtualDataTable } from "./VirtualDataTable";
import {
  buildRowSelectionKey,
  collectSelectedPrimaryKeyRows,
  primaryKeysToStableRowKey,
  buildPendingChangeKey,
  getRecordPrimaryKeys,
  sameRowSelectionKeys,
} from "./tableDataRowKeys";
import {
  assertCsvRowWithinLimit,
  buildQueryResultWorkbookBase64,
  saveExcelWithDialog,
} from "../../utils/excelExport";
import {
  normalizeValue,
  displayVal,
  visualizeInvisibleChars,
  filterVisibleColumns,
  searchColumns,
  TABLE_HEIGHT_MIN,
  TABLE_HEIGHT_MAX,
  TABLE_RESIZE_BAR_HEIGHT,
  loadStoredUserTableHeight,
  saveUserTableHeight,
  clampUserTableHeight,
  isTrustedTableSlotMeasure,
  stabilizeTableSlotHeight,
  tableSlotMaxUserHeightOrNull,
  getLastTrustedTableSlotHeight,
  setLastTrustedTableSlotHeight,
} from "./tableDataUtils";
import { MemoEditableCell } from "./EditableCell";
import { TAB_NAVIGATE_EDIT } from "./tableDataEditEvents";
import { getDatabaseCapabilities } from "../../utils/databaseCapabilities";
import { normalizeDatabaseType } from "../../utils/connectionConfig";
import { describeAutoGeneratedColumn } from "./tableDataColumnHints";

const { Text } = Typography;

/** 表数据分页：每页行数上限（与自定义输入框一致） */
const TABLE_PAGE_SIZE_MAX = 10000;

/** 稳定的空设置引用，避免 Zustand selector 因返回新对象导致无限重渲染 */
const EMPTY_TABLE_SETTINGS = {
  columnWidths: {} as Record<string, number>,
  hiddenColumns: [] as string[],
};
const EMPTY_SELECTED_ROW_KEYS: string[] = [];
/** 行选择列宽度（行+列虚拟化由 VirtualDataTable 内部统一处理，通过 rowSelection.columnWidth 透传） */
const ROW_SELECTION_COL_WIDTH = 48;

/** 排序指示器：使用 Unicode 字符替代图标组件，减少 DOM 与 React 开销 */
function SortIndicator({
  active,
  direction,
  priority,
  ariaLabel,
  title,
  onClick,
}: {
  active: boolean;
  direction?: "ASC" | "DESC";
  /** 从 1 开始；多列排序时显示优先级序号 */
  priority?: number;
  ariaLabel?: string;
  title?: string;
  onClick: (e: ReactMouseEvent<HTMLSpanElement>) => void;
}) {
  const upColor =
    active && direction === "ASC" ? "#1677ff" : "var(--text-muted)";
  const downColor =
    active && direction === "DESC" ? "#1677ff" : "var(--text-muted)";
  return (
    <span
      role="button"
      aria-label={ariaLabel ?? "点击排序"}
      title={title ?? "排序"}
      onClick={(e) => {
        e.stopPropagation();
        onClick(e);
      }}
      style={{
        display: "inline-flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        cursor: "pointer",
        padding: "0 2px",
        marginLeft: 2,
        lineHeight: 1,
        flexShrink: 0,
        fontSize: 9,
        position: "relative",
      }}
    >
      {priority != null && priority > 0 ? (
        <span
          style={{
            position: "absolute",
            right: -1,
            top: -6,
            fontSize: 8,
            lineHeight: 1,
            color: "var(--text-muted)",
            fontWeight: 600,
          }}
        >
          {priority}
        </span>
      ) : null}
      <span style={{ color: upColor }}>▲</span>
      <span style={{ color: downColor, marginTop: -2 }}>▼</span>
    </span>
  );
}

// 主表的列宽调节由 VirtualDataTable 内部 ColumnResizer 实现，这里不再需要 ResizableTitle。
// 表格高度持久化、slot 测量稳定化等纯函数已抽离到 ./tableDataUtils。

export function TableData() {
  const activeConnection = useConnectionStore((s) => s.activeConnection);
  const clientReadOnly = useClientReadOnly();
  const {
    selectedDatabase,
    selectedTable,
    tableStructure,
    tableContentActiveTab,
  } = useDatabaseStore(
    useShallow((s) => ({
      selectedDatabase: s.selectedDatabase,
      selectedTable: s.selectedTable,
      tableStructure: s.tableStructure,
      tableContentActiveTab: s.tableContentActiveTab,
    }))
  );
  const {
    columns,
    rows,
    total,
    page,
    pageSize,
    sortFields,
    whereClause,
    filterRows,
    dataLoading,
    totalCountLoading,
    totalCountStale,
    dataError,
    executionTime,
    activeTableKey,
    pendingChangesCache,
    rowSelectionCache,
    _filterTrigger,
  } = useTableDataStore(
    useShallow((s) => ({
      columns: s.columns,
      rows: s.rows,
      total: s.total,
      page: s.page,
      pageSize: s.pageSize,
      sortFields: s.sortFields,
      whereClause: s.whereClause,
      filterRows: s.filterRows,
      dataLoading: s.dataLoading,
      totalCountLoading: s.totalCountLoading,
      totalCountStale: s.totalCountStale,
      dataError: s.dataError,
      executionTime: s.executionTime,
      activeTableKey: s.activeTableKey,
      pendingChangesCache: s.pendingChangesCache,
      rowSelectionCache: s.rowSelectionCache,
      _filterTrigger: s._filterTrigger,
    }))
  );
  const {
    loadData,
    refreshPagination,
    setPage,
    setPageSize,
    toggleSortColumn,
    setSort,
    removeSortField,
    shiftSortFieldPriority,
    setWhereClause,
    batchUpdateCells,
    insertRow,
    deleteRows,
    switchToTable,
    setPendingChange,
    removePendingChange,
    clearPendingChanges,
    setRowSelection,
    clearRowSelection,
  } = useTableDataStore(
    useShallow((s) => ({
      loadData: s.loadData,
      refreshPagination: s.refreshPagination,
      setPage: s.setPage,
      setPageSize: s.setPageSize,
      toggleSortColumn: s.toggleSortColumn,
      setSort: s.setSort,
      removeSortField: s.removeSortField,
      shiftSortFieldPriority: s.shiftSortFieldPriority,
      setWhereClause: s.setWhereClause,
      batchUpdateCells: s.batchUpdateCells,
      insertRow: s.insertRow,
      deleteRows: s.deleteRows,
      switchToTable: s.switchToTable,
      setPendingChange: s.setPendingChange,
      removePendingChange: s.removePendingChange,
      clearPendingChanges: s.clearPendingChanges,
      setRowSelection: s.setRowSelection,
      clearRowSelection: s.clearRowSelection,
    }))
  );

  const [insertModalOpen, setInsertModalOpen] = useState(false);
  const [insertForm] = Form.useForm();
  const [messageApi, contextHolder] = message.useMessage();

  const connId = activeConnection?.connId ?? "";
  const stableConnId = activeConnection?.config.id ?? connId;
  const database = selectedDatabase ?? "";
  const table = selectedTable ?? "";
  const capabilities = useMemo(
    () => getDatabaseCapabilities(activeConnection?.config.database_type),
    [activeConnection?.config.database_type]
  );
  const currentDatabaseType = normalizeDatabaseType(
    activeConnection?.config.database_type
  );
  const isClickHouse = currentDatabaseType === "clickhouse";
  /**
   * 当前表是否具备「按主键定位的写操作」前置条件：
   * - 已加载结构（避免在结构尚未到位时误判为"无主键"）
   * - 至少存在一个主键列
   * SQLite 阶段四要求无主键表不开放可视化编辑，因此新增/更新/删除统一禁用。
   */
  const rowLocatorColumnsForEdits = useMemo(
    () =>
      tableStructure
        ?.filter(
          (c) =>
            c.key === "PRI" ||
            (currentDatabaseType === "sqlserver" && c.key === "UNI")
        )
        .map((c) => c.name) ?? [],
    [tableStructure, currentDatabaseType]
  );
  const hasRowLocatorForEdits = rowLocatorColumnsForEdits.length > 0;
  const requiresPrimaryKeyForDataEditing =
    currentDatabaseType === "sqlite" || currentDatabaseType === "sqlserver";
  const baseDataEditingAllowed =
    !clientReadOnly && capabilities.tableDataEditing;
  const dataEditingAllowed =
    baseDataEditingAllowed &&
    (!requiresPrimaryKeyForDataEditing || hasRowLocatorForEdits);
  const insertAllowed =
    dataEditingAllowed || (isClickHouse && !clientReadOnly);
  const noPrimaryKeyDisabledReason =
    currentDatabaseType === "sqlserver"
      ? "该表没有主键或非过滤唯一索引，无法定位行；请改用 SQL 编辑器或为表添加主键/唯一索引"
      : "该表没有主键，无法定位行；请改用 SQL 编辑器或为表添加主键";
  const rowEditDisabledReason = !capabilities.tableDataEditing
    ? "当前数据库类型不允许编辑表数据"
    : clientReadOnly
      ? "当前连接为只读模式，不允许编辑表数据"
      : !hasRowLocatorForEdits
        ? noPrimaryKeyDisabledReason
        : "";
  const insertDisabledReason = isClickHouse
    ? clientReadOnly
      ? "当前连接为只读模式，不允许新增行"
      : ""
    : !capabilities.tableDataEditing
      ? "当前数据库类型不允许编辑表数据"
      : clientReadOnly
        ? "当前连接为只读模式，不允许编辑表数据"
        : requiresPrimaryKeyForDataEditing && !hasRowLocatorForEdits
          ? noPrimaryKeyDisabledReason
          : "";
  const rowOperationsAllowed = baseDataEditingAllowed && hasRowLocatorForEdits;
  const rowSelectionScopeKey =
    connId && database && table ? `${connId}|${database}|${table}` : "";
  const selectedRowKeys = useMemo(
    () =>
      rowSelectionScopeKey
        ? (rowSelectionCache[rowSelectionScopeKey] ?? EMPTY_SELECTED_ROW_KEYS)
        : EMPTY_SELECTED_ROW_KEYS,
    [rowSelectionCache, rowSelectionScopeKey]
  );

  const setSelectedRowKeysForCurrentScope = useCallback(
    (nextKeys: string[] | ((prev: string[]) => string[])) => {
      if (!connId || !database || !table) return;
      const currentKeys = rowSelectionScopeKey
        ? (rowSelectionCache[rowSelectionScopeKey] ?? [])
        : [];
      const resolvedKeys =
        typeof nextKeys === "function" ? nextKeys(currentKeys) : nextKeys;

      if (sameRowSelectionKeys(currentKeys, resolvedKeys)) {
        return;
      }

      if (resolvedKeys.length === 0) {
        clearRowSelection(connId, database, table);
        return;
      }

      setRowSelection(connId, database, table, resolvedKeys);
    },
    [
      clearRowSelection,
      connId,
      database,
      rowSelectionCache,
      rowSelectionScopeKey,
      setRowSelection,
      table,
    ]
  );

  // 固定 rowKey / rowSelection 引用，避免每次 render 生成新对象破坏 VirtualDataTable 的 memo
  const vdtRowKey = useCallback(
    (record: Record<string, unknown>) => String(record._selectionKey),
    []
  );
  const handleRowSelectionChange = useCallback(
    (keys: string[]) => setSelectedRowKeysForCurrentScope(keys),
    [setSelectedRowKeysForCurrentScope]
  );
  const vdtRowSelection = useMemo(
    () =>
      clientReadOnly
        ? undefined
        : {
            selectedRowKeys,
            onChange: handleRowSelectionChange,
            columnWidth: ROW_SELECTION_COL_WIDTH,
          },
    [clientReadOnly, selectedRowKeys, handleRowSelectionChange]
  );

  // 列宽与列可见性：使用稳定的 config.id 作为 key（connId 每次连接都是新 UUID，无法跨会话持久化）
  const tableKey =
    stableConnId && database && table
      ? `${stableConnId}|${database}|${table}`
      : "";
  const storedSettings = useTableColumnSettingsStore(
    (s: { settings: Record<string, TableColumnSettings> }) =>
      tableKey ? (s.settings[tableKey] ?? EMPTY_TABLE_SETTINGS) : null
  );
  const {
    setColumnWidth: setStoreColumnWidth,
    setHiddenColumns: setStoreHiddenColumns,
    toggleColumnVisibility: storeToggleColumnVisibility,
  } = useTableColumnSettingsStore(
    useShallow((s) => ({
      setColumnWidth: s.setColumnWidth,
      setHiddenColumns: s.setHiddenColumns,
      toggleColumnVisibility: s.toggleColumnVisibility,
    }))
  );

  const columnWidths = useMemo(() => {
    if (!storedSettings || !columns.length) return {};
    const widths: Record<string, number> = {};
    for (const col of columns) {
      if (storedSettings.columnWidths[col] != null) {
        widths[col] = storedSettings.columnWidths[col];
      }
    }
    return widths;
  }, [storedSettings, columns]);

  // 全部列名（从 tableStructure 获取，而非查询结果）用于列设置 UI 和 selectColumns 计算
  const allColumnNames = useMemo(
    () => tableStructure?.map((c) => c.name) ?? [],
    [tableStructure]
  );

  const hiddenColumns = useMemo(() => {
    if (!storedSettings || !allColumnNames.length) return new Set<string>();
    const colSet = new Set(allColumnNames);
    return new Set(
      storedSettings.hiddenColumns.filter((c: string) => colSet.has(c))
    );
  }, [storedSettings, allColumnNames]);

  // 计算 selectColumns：有隐藏列时仅查询可见列（后端自动合并主键列），否则 undefined 使用 SELECT *
  const selectColumns = useMemo(() => {
    if (!allColumnNames.length || hiddenColumns.size === 0) return undefined;
    return allColumnNames.filter((c) => !hiddenColumns.has(c));
  }, [allColumnNames, hiddenColumns]);

  const [columnSearchText, setColumnSearchText] = useState("");
  const [showInvisibleChars, setShowInvisibleChars] = useState(false);

  const [reviewModalOpen, setReviewModalOpen] = useState(false);
  const [submitLoading, setSubmitLoading] = useState(false);

  // 表格容器 ref + 动态高度（配合 virtual 虚拟滚动）
  const tableSlotRef = useRef<HTMLDivElement>(null);
  const tableContainerRef = useRef<HTMLDivElement>(null);
  const [tableHeight] = useState(400);
  // 用户通过拖拽 resize bar 设定的表格高度（null 表示自动撑满）。持久化到 localStorage。
  const [userTableHeight, setUserTableHeight] = useState<number | null>(() =>
    loadStoredUserTableHeight()
  );
  const [isResizing, setIsResizing] = useState(false);
  const [tableSlotHeight, setTableSlotHeight] = useState<number>(() =>
    isTrustedTableSlotMeasure(getLastTrustedTableSlotHeight())
      ? getLastTrustedTableSlotHeight()
      : 0
  );
  const maxUserTableHeightRef = useRef<number>(TABLE_HEIGHT_MAX);
  /** 上一次可信的 slot 像素高度（用于 Tab 切回时前几帧读数为 0 的恢复） */
  const lastTrustedSlotHeightRef = useRef(
    isTrustedTableSlotMeasure(getLastTrustedTableSlotHeight())
      ? getLastTrustedTableSlotHeight()
      : 0
  );

  // 获取主键列（memoized）
  const primaryKeyColumns = rowLocatorColumnsForEdits;
  const primaryKeyColumn = primaryKeyColumns[0] ?? "";

  /** 列名 → MySQL column_type（用于 varchar 等大整数字符串列不因 Number/JSON 丢精度） */
  const columnTypesByName = useMemo(
    () =>
      tableStructure
        ? Object.fromEntries(tableStructure.map((c) => [c.name, c.column_type]))
        : ({} as Record<string, string>),
    [tableStructure]
  );

  const pendingChanges = useMemo(
    () =>
      connId && database && table
        ? new Map(
            Object.entries(
              pendingChangesCache[`${connId}|${database}|${table}`] ?? {}
            )
          )
        : new Map<string, PendingChange>(),
    [connId, database, table, pendingChangesCache]
  );
  const pendingCount = pendingChanges.size;
  const enabledFilterCount = useMemo(() => {
    const rows = filterRows ?? [];
    const n = rows.filter((r) => r.enabled !== false).length;
    // whereClause 存在但 rows 为空时（历史数据/兼容路径），至少展示 1，避免“已筛选但无徽标”
    if (n === 0 && whereClause.trim()) return 1;
    return n;
  }, [filterRows, whereClause]);
  const hasActiveFilter =
    enabledFilterCount > 0 && whereClause.trim().length > 0;

  // 筛选弹窗（点击工具栏筛选图标打开；保存后应用筛选）
  const [filterModalOpen, setFilterModalOpen] = useState(false);
  /** 查看当前筛选对应查询 SQL（弹窗） */
  const [filterSqlPreviewOpen, setFilterSqlPreviewOpen] = useState(false);

  // 当表切换时，重置列设置搜索框（列宽和列可见性由持久化 store 按表加载）
  useEffect(() => {
    setColumnSearchText("");
  }, [connId, database, table]);

  useEffect(() => {
    if (clientReadOnly) {
      setSelectedRowKeysForCurrentScope([]);
    }
  }, [clientReadOnly, setSelectedRowKeysForCurrentScope]);

  // 仅在「数据」Tab 可见时监听尺寸；读数不可信时不更新（见 TABLE_SLOT_MEASURE_TRUST_MIN）。
  useEffect(() => {
    if (tableContentActiveTab !== "data") return;
    const slot = tableSlotRef.current;
    if (!slot) return;
    const observer = new ResizeObserver((entries) => {
      const entry = entries[0];
      if (!entry) return;
      const raw = entry.contentRect.height;
      if (!isTrustedTableSlotMeasure(raw)) return;
      requestAnimationFrame(() => {
        setTableSlotHeight((prev) => {
          const next = stabilizeTableSlotHeight(prev, raw);
          if (isTrustedTableSlotMeasure(next)) {
            lastTrustedSlotHeightRef.current = next;
            setLastTrustedTableSlotHeight(next);
          }
          return next;
        });
      });
    });
    observer.observe(slot);
    return () => observer.disconnect();
  }, [tableContentActiveTab]);

  // Tab / 表上下文变化后主动测量；前几帧可能仍为 0，需 rAF 重试或回退到 lastTrusted。
  useLayoutEffect(() => {
    if (tableContentActiveTab !== "data") return;
    const SLOT_REMREASURE_MAX_FRAMES = 15;
    let cancelled = false;
    let frames = 0;

    const tick = () => {
      if (cancelled) return;
      const el = tableSlotRef.current;
      if (!el) return;
      const raw = el.getBoundingClientRect().height;
      if (isTrustedTableSlotMeasure(raw)) {
        lastTrustedSlotHeightRef.current = raw;
        setLastTrustedTableSlotHeight(raw);
        setTableSlotHeight((prev) => stabilizeTableSlotHeight(prev, raw));
        return;
      }
      frames += 1;
      if (frames < SLOT_REMREASURE_MAX_FRAMES) {
        requestAnimationFrame(tick);
      } else if (isTrustedTableSlotMeasure(lastTrustedSlotHeightRef.current)) {
        setTableSlotHeight(lastTrustedSlotHeightRef.current);
      }
    };

    tick();
    return () => {
      cancelled = true;
    };
  }, [tableContentActiveTab, connId, database, table]);

  // 表格 slot 高度变化时，更新用户可拖拽的最大高度（slotHeight - resizeBarHeight）。
  // tableSlotHeight 为 0 或未布局完成时不可更新：否则 max 会变成 TABLE_HEIGHT_MIN，手动高度会在后续渲染被错误 clamp。
  useEffect(() => {
    const maxInSlot = tableSlotMaxUserHeightOrNull(tableSlotHeight);
    if (maxInSlot == null) return;
    maxUserTableHeightRef.current = maxInSlot;
  }, [tableSlotHeight]);

  // 自动模式下表格高度 = slotHeight - resizeBarHeight（保证 bar 始终可见）
  const autoTableHeight = Math.max(
    TABLE_HEIGHT_MIN,
    (tableSlotHeight || tableHeight) - TABLE_RESIZE_BAR_HEIGHT
  );

  // 表格实际渲染高度：优先用用户拖拽设定的值（并按 slot 最大值 clamp），否则用自动高度
  const effectiveTableHeight =
    userTableHeight != null
      ? Math.min(userTableHeight, maxUserTableHeightRef.current)
      : autoTableHeight;

  // 拖拽 resize bar：mousedown 后跟踪 document 级 mousemove，松开时落地 localStorage
  const handleResizeStart = useCallback(
    (e: React.MouseEvent<HTMLDivElement>) => {
      e.preventDefault();
      e.stopPropagation();
      const startY = e.clientY;
      const startHeight = effectiveTableHeight;
      setIsResizing(true);
      const onMouseMove = (mv: MouseEvent) => {
        const delta = mv.clientY - startY;
        const next = clampUserTableHeight(startHeight + delta);
        const maxInSlot = maxUserTableHeightRef.current;
        const nextInSlot = Math.min(next, maxInSlot);
        setUserTableHeight(nextInSlot);
      };
      const onMouseUp = () => {
        document.removeEventListener("mousemove", onMouseMove, true);
        document.removeEventListener("mouseup", onMouseUp, true);
        document.body.style.cursor = "";
        document.body.style.userSelect = "";
        setIsResizing(false);
        // useState 异步：用同步 ref 不可行，这里读最新 userTableHeight 由下方 effect 持久化
      };
      document.addEventListener("mousemove", onMouseMove, true);
      document.addEventListener("mouseup", onMouseUp, true);
      document.body.style.cursor = "row-resize";
      document.body.style.userSelect = "none";
    },
    [effectiveTableHeight]
  );

  // 双击 resize bar：重置为自动撑满模式
  const handleResizeReset = useCallback(() => {
    setUserTableHeight(null);
  }, []);

  // 持久化 userTableHeight 到 localStorage
  useEffect(() => {
    saveUserTableHeight(userTableHeight);
  }, [userTableHeight]);

  // selectColumns ref：保证 effect 中始终使用最新值，同时不触发额外 re-render
  const selectColumnsRef = useRef(selectColumns);
  selectColumnsRef.current = selectColumns;
  const sortFieldsSerialized = useMemo(
    () =>
      sortFields
        .map((f) => `${encodeURIComponent(f.column)}:${f.order}`)
        .join("|"),
    [sortFields]
  );

  const queryEffectStateRef = useRef<{
    tableKey: string;
    page: number;
    pageSize: number;
    sortFieldsSerialized: string;
    whereClause: string;
    filterTrigger: number;
    activeTab: string;
  } | null>(null);
  const skipRestoredQueryForTableRef = useRef<string | null>(null);

  // 当表切换时：先尝试从缓存恢复，否则加载数据。仅在数据 tab 激活时加载，避免切换到结构/SQL 等 tab 时发起 count 请求
  const restoredFromCacheRef = useRef(false);
  useLayoutEffect(() => {
    if (connId && database && table) {
      const fromCache = switchToTable(connId, database, table);
      if (!fromCache && tableContentActiveTab === "data") {
        loadData(connId, database, table, selectColumnsRef.current);
        restoredFromCacheRef.current = false;
      } else if (fromCache) {
        restoredFromCacheRef.current = true;
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [connId, database, table, tableContentActiveTab]);

  // tableStructure 就绪后，如果有隐藏列且首次加载使用了 SELECT *，则用优化列重新加载。仅在数据 tab 时加载
  const hasReloadedForColumns = useRef(false);
  useEffect(() => {
    if (!connId || !database || !table || tableContentActiveTab !== "data")
      return;
    if (hasReloadedForColumns.current) return;
    if (restoredFromCacheRef.current) {
      hasReloadedForColumns.current = true;
      return;
    }
    if (selectColumns && selectColumns.length > 0) {
      hasReloadedForColumns.current = true;
      loadData(connId, database, table, selectColumns);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectColumns, tableContentActiveTab]);
  // 表切换时重置标记
  useEffect(() => {
    hasReloadedForColumns.current = false;
  }, [connId, database, table]);

  // 分页/排序/筛选变化时重新加载 & 清空待提交。表切换会同时恢复 page/whereClause 等查询状态，
  // 但那属于切表恢复上下文，不应清理任何表的待提交修改。
  useEffect(() => {
    const currentTableKey =
      connId && database && table ? `${connId}|${database}|${table}` : "";
    const nextQueryState = {
      tableKey: currentTableKey,
      page,
      pageSize,
      sortFieldsSerialized,
      whereClause,
      filterTrigger: _filterTrigger,
      activeTab: tableContentActiveTab,
    };
    const previous = queryEffectStateRef.current;

    if (!currentTableKey || tableContentActiveTab !== "data") {
      queryEffectStateRef.current = nextQueryState;
      skipRestoredQueryForTableRef.current = null;
      if (restoredFromCacheRef.current) restoredFromCacheRef.current = false;
      return;
    }

    if (activeTableKey && activeTableKey !== currentTableKey) {
      queryEffectStateRef.current = nextQueryState;
      skipRestoredQueryForTableRef.current = currentTableKey;
      return;
    }

    if (!previous) {
      queryEffectStateRef.current = nextQueryState;
      if (restoredFromCacheRef.current) restoredFromCacheRef.current = false;
      return;
    }

    if (previous.tableKey !== currentTableKey) {
      queryEffectStateRef.current = nextQueryState;
      skipRestoredQueryForTableRef.current = currentTableKey;
      return;
    }

    const queryChanged =
      previous.page !== page ||
      previous.pageSize !== pageSize ||
      previous.sortFieldsSerialized !== sortFieldsSerialized ||
      previous.whereClause !== whereClause ||
      previous.filterTrigger !== _filterTrigger ||
      previous.activeTab !== tableContentActiveTab;

    if (!queryChanged) {
      queryEffectStateRef.current = nextQueryState;
      if (skipRestoredQueryForTableRef.current === currentTableKey) {
        skipRestoredQueryForTableRef.current = null;
      }
      if (restoredFromCacheRef.current) restoredFromCacheRef.current = false;
      return;
    }

    if (
      restoredFromCacheRef.current ||
      skipRestoredQueryForTableRef.current === currentTableKey
    ) {
      restoredFromCacheRef.current = false;
      skipRestoredQueryForTableRef.current = null;
      queryEffectStateRef.current = nextQueryState;
      return;
    }

    queryEffectStateRef.current = nextQueryState;
    loadData(connId, database, table, selectColumnsRef.current);
    clearPendingChanges(connId, database, table);
  }, [
    activeTableKey,
    clearPendingChanges,
    connId,
    database,
    table,
    loadData,
    page,
    pageSize,
    sortFieldsSerialized,
    whereClause,
    _filterTrigger,
    tableContentActiveTab,
  ]);

  // 刷新数据
  const handleRefresh = useCallback(() => {
    if (connId && database && table) {
      loadData(connId, database, table, selectColumnsRef.current);
      clearPendingChanges(connId, database, table);
    }
  }, [clearPendingChanges, connId, database, table, loadData]);

  // 刷新分页（仅重新统计总行数）
  const handleRefreshPagination = useCallback(async () => {
    if (!connId || !database || !table) return;
    try {
      await refreshPagination(connId, database, table);
      messageApi.success("分页已刷新");
    } catch {
      messageApi.error("刷新分页失败");
    }
  }, [connId, database, table, refreshPagination, messageApi]);

  // 添加/更新/移除一条待提交修改
  const handleCellEdit = useCallback(
    (
      rowKey: number,
      colName: string,
      oldValue: unknown,
      newValue: unknown,
      primaryKeys: Record<string, unknown>
    ) => {
      if (!connId || !database || !table) return;
      const key = buildPendingChangeKey(primaryKeys, colName);
      if (newValue === oldValue) {
        removePendingChange(connId, database, table, key);
        return;
      }
      setPendingChange(connId, database, table, key, {
        rowKey,
        colName,
        oldValue,
        newValue,
        primaryKeys,
      });
    },
    [connId, database, table, removePendingChange, setPendingChange]
  );

  // 撤销全部待提交修改
  const handleDiscardAll = useCallback(() => {
    if (!connId || !database || !table) return;
    clearPendingChanges(connId, database, table);
  }, [clearPendingChanges, connId, database, table]);

  // 从 review Modal 中移除一条修改
  const handleRemovePending = useCallback(
    (key: string) => {
      if (!connId || !database || !table) return;
      removePendingChange(connId, database, table, key);
    },
    [connId, database, removePendingChange, table]
  );

  // 在 review Modal 中修改某条记录的新值
  const handleUpdatePendingValue = useCallback(
    (key: string, newValue: unknown) => {
      if (!connId || !database || !table) return;
      const change = pendingChanges.get(key);
      if (!change) return;
      if (newValue === change.oldValue) {
        removePendingChange(connId, database, table, key);
        return;
      }
      setPendingChange(connId, database, table, key, { ...change, newValue });
    },
    [
      connId,
      database,
      pendingChanges,
      removePendingChange,
      setPendingChange,
      table,
    ]
  );

  // 批量提交所有待提交修改：每行合并为一次 update（多列合并为一条 SQL），
  // 整批在后端单个事务中执行——要么全部成功，要么整批回滚，避免部分提交。
  const handleSubmitAll = useCallback(async () => {
    if (pendingChanges.size === 0) return;
    if (!connId || !database || !table) return;

    const byRow = new Map<
      string,
      { primaryKeys: Record<string, unknown>; updates: Record<string, unknown> }
    >();
    let skippedNoPk = 0;
    for (const [, change] of pendingChanges) {
      if (Object.keys(change.primaryKeys).length === 0) {
        skippedNoPk++;
        continue;
      }
      const key = primaryKeysToStableRowKey(change.primaryKeys);
      const row = byRow.get(key);
      if (row) {
        row.updates[change.colName] = change.newValue;
      } else {
        byRow.set(key, {
          primaryKeys: change.primaryKeys,
          updates: { [change.colName]: change.newValue },
        });
      }
    }

    const rows = Array.from(byRow.values());
    if (rows.length === 0) {
      setReviewModalOpen(false);
      messageApi.warning("没有可提交的修改（缺少主键信息）");
      return;
    }

    setSubmitLoading(true);
    try {
      await batchUpdateCells(connId, database, table, rows);
      // 整批成功后才清空待提交修改
      clearPendingChanges(connId, database, table);
      setReviewModalOpen(false);
      if (skippedNoPk > 0) {
        messageApi.warning(
          `${rows.length} 行提交成功，${skippedNoPk} 项因缺少主键被跳过`
        );
      } else {
        messageApi.success(`全部 ${rows.length} 行修改提交成功`);
      }
    } catch (e) {
      // 整批回滚，保留待提交修改以便用户重试或修正
      messageApi.error(`提交失败，已整批回滚：${String(e)}`);
    } finally {
      setSubmitLoading(false);
    }
  }, [
    clearPendingChanges,
    pendingChanges,
    connId,
    database,
    table,
    batchUpdateCells,
    messageApi,
  ]);

  // 列宽调节 (原生 mousedown 实现)，持久化到 store
  const handleResize = useCallback(
    (colName: string) => (newWidth: number) => {
      setStoreColumnWidth(stableConnId, database, table, colName, newWidth);
    },
    [stableConnId, database, table, setStoreColumnWidth]
  );

  // 列可见性切换，持久化到 store。显示原来隐藏的列时触发重新加载（因其数据未被查询）
  const toggleColumnVisibility = useCallback(
    (colName: string) => {
      const wasHidden = hiddenColumns.has(colName);
      storeToggleColumnVisibility(
        stableConnId,
        database,
        table,
        colName,
        hiddenColumns
      );
      if (wasHidden && connId && database && table) {
        const newHidden = new Set(hiddenColumns);
        newHidden.delete(colName);
        const newSelectCols =
          newHidden.size === 0
            ? undefined
            : allColumnNames.filter((c) => !newHidden.has(c));
        loadData(connId, database, table, newSelectCols);
      }
    },
    [
      stableConnId,
      database,
      table,
      hiddenColumns,
      storeToggleColumnVisibility,
      connId,
      allColumnNames,
      loadData,
    ]
  );

  // 使用 ref 保存频繁变化的数据，避免 tableColumns 的 useMemo 因 pendingChanges 变化频繁重建
  const pendingChangesRef = useRef(pendingChanges);
  pendingChangesRef.current = pendingChanges;
  const messageApiRef = useRef(messageApi);
  messageApiRef.current = messageApi;

  // 可见列名（按显示顺序），用于 Tab 导航计算
  const visibleColNames = useMemo(
    () => columns.filter((c) => !hiddenColumns.has(c)),
    [columns, hiddenColumns]
  );

  // Tab 导航：根据当前 cellKey 和方向计算下一格并派发自定义事件
  const handleTabNavigate = useCallback(
    (cellKey: string, direction: "next" | "prev") => {
      const firstColon = cellKey.indexOf(":");
      if (firstColon < 0) return;
      const rowKey = cellKey.slice(0, firstColon);
      const colName = cellKey.slice(firstColon + 1);
      const idx = visibleColNames.indexOf(colName);
      if (idx < 0) return;
      const nextIdx = direction === "next" ? idx + 1 : idx - 1;
      if (nextIdx < 0 || nextIdx >= visibleColNames.length) return;
      const nextColName = visibleColNames[nextIdx];
      const nextCellKey = `${rowKey}:${nextColName}`;
      document.dispatchEvent(
        new CustomEvent(TAB_NAVIGATE_EDIT, { detail: nextCellKey })
      );
    },
    [visibleColNames]
  );

  const handleCopyColumnName = useCallback(
    async (name: string) => {
      try {
        await copyTextWithBreadcrumb(name, "table-data-column-header", {
          column: name,
        });
        messageApi.success("已复制字段名");
      } catch {
        messageApi.error("复制失败");
      }
    },
    [messageApi]
  );

  // 构建表头列定义（memoized，不依赖 pendingChanges —— 通过 ref 访问最新值）
  const DEFAULT_COL_WIDTH = 160;
  const allTableColumns = useMemo<ColumnsType<Record<string, unknown>>>(
    () =>
      columns.map((colName) => {
        const colWidth = columnWidths[colName] ?? DEFAULT_COL_WIDTH;
        const columnComment = tableStructure?.find(
          (c) => c.name === colName
        )?.comment;
        const sortIdx = sortFields.findIndex((f) => f.column === colName);
        const sortEntry = sortIdx >= 0 ? sortFields[sortIdx]! : undefined;
        const isSortActive = !!sortEntry;
        const sortPriority =
          sortFields.length > 1 && sortIdx >= 0 ? sortIdx + 1 : undefined;
        const colDef: ColumnType<Record<string, unknown>> = {
          title: (
            <span
              style={{
                display: "inline-flex",
                alignItems: "center",
                minWidth: 0,
              }}
            >
              <Tooltip title={columnComment || "无注释"}>
                <span
                  style={{
                    display: "inline-flex",
                    alignItems: "center",
                    gap: 4,
                    minWidth: 0,
                    overflow: "hidden",
                    textOverflow: "ellipsis",
                  }}
                >
                  {primaryKeyColumns.includes(colName) && (
                    <span
                      style={{ color: "#faad14", fontSize: 10, flexShrink: 0 }}
                    >
                      PK
                    </span>
                  )}
                  <span
                    style={{
                      fontSize: 12,
                      overflow: "hidden",
                      textOverflow: "ellipsis",
                    }}
                  >
                    {colName}
                  </span>
                </span>
              </Tooltip>
              <Tooltip title="复制字段名">
                <Button
                  type="text"
                  size="small"
                  icon={<CopyOutlined style={{ fontSize: 11 }} />}
                  aria-label={`复制字段名 ${colName}`}
                  onClick={(e) => {
                    e.stopPropagation();
                    void handleCopyColumnName(colName);
                  }}
                  style={{
                    flexShrink: 0,
                    paddingInline: 2,
                    height: 22,
                    minWidth: 22,
                  }}
                />
              </Tooltip>
              <SortIndicator
                active={isSortActive}
                direction={sortEntry?.order}
                priority={sortPriority}
                ariaLabel={`${colName} 字段排序`}
                title={
                  sortFields.length > 1
                    ? "单击：主排序；Shift 或 ⌘+单击：对该列次要排序（或切换/移除）。可在工具栏调整优先级。"
                    : "单击：按该列排序；Shift 或 ⌘+单击：追加次要排序键。可在工具栏调整优先级。"
                }
                onClick={(e) => {
                  restoredFromCacheRef.current = false;
                  toggleSortColumn(colName, e.shiftKey || e.metaKey);
                }}
              />
            </span>
          ),
          dataIndex: colName,
          key: colName,
          ellipsis: true,
          width: colWidth,
          onHeaderCell: () => ({
            width: colWidth,
            onResize: handleResize(colName),
          }),
          render: (_, record: Record<string, unknown>) => {
            const rowKey = record._rowKey as number;
            const cellValue = record[colName];
            const pks = getRecordPrimaryKeys(record, primaryKeyColumns);
            const pendingKey =
              Object.keys(pks).length > 0
                ? buildPendingChangeKey(pks, colName)
                : "";
            const pending = pendingKey
              ? pendingChangesRef.current.get(pendingKey)
              : undefined;
            const displayValue = pending ? pending.newValue : cellValue;
            const renderedText =
              showInvisibleChars && typeof displayValue === "string"
                ? visualizeInvisibleChars(displayValue)
                : undefined;

            return (
              <MemoEditableCell
                key={`${rowSelectionScopeKey}:${pendingKey || `${rowKey}:${colName}`}`}
                value={cellValue}
                pendingValue={pending?.newValue}
                hasPending={!!pending}
                cellKey={`${rowKey}:${colName}`}
                fieldLabel={colName}
                readOnly={!rowOperationsAllowed}
                forceStringSemantics={isStringColumnType(
                  columnTypesByName[colName] ?? ""
                )}
                onTabNavigate={handleTabNavigate}
                displayText={renderedText}
                onEdit={(newValue) => {
                  if (Object.keys(pks).length === 0) {
                    messageApiRef.current.warning(noPrimaryKeyDisabledReason);
                    return;
                  }

                  handleCellEdit(rowKey, colName, cellValue, newValue, pks);
                }}
              />
            );
          },
        };
        return colDef;
      }),
    [
      columns,
      columnWidths,
      tableStructure,
      primaryKeyColumns,
      sortFields,
      handleResize,
      toggleSortColumn,
      handleTabNavigate,
      handleCopyColumnName,
      handleCellEdit,
      rowOperationsAllowed,
      noPrimaryKeyDisabledReason,
      showInvisibleChars,
      columnTypesByName,
      rowSelectionScopeKey,
    ]
  );

  // 过滤隐藏列
  const tableColumns = useMemo(
    () => filterVisibleColumns(allTableColumns, hiddenColumns),
    [allTableColumns, hiddenColumns]
  );

  // 把行数据从 array-of-arrays 转为 array-of-objects（memoized）
  const dataSource = useMemo<Record<string, unknown>[]>(
    () =>
      rows.map((row, rowIdx) => {
        const record: Record<string, unknown> = { _rowKey: rowIdx };
        columns.forEach((col, colIdx) => {
          record[col] = row[colIdx];
        });
        record._selectionKey = buildRowSelectionKey(
          rowSelectionScopeKey,
          primaryKeyColumns,
          record,
          rowIdx,
          page
        );
        return record;
      }),
    [rows, columns, rowSelectionScopeKey, primaryKeyColumns, page]
  );

  useEffect(() => {
    if (activeTableKey !== rowSelectionScopeKey) {
      return;
    }
    if (clientReadOnly) {
      setSelectedRowKeysForCurrentScope([]);
      return;
    }
    const validSelectionKeys = new Set(
      dataSource.map((row) => String(row._selectionKey))
    );
    setSelectedRowKeysForCurrentScope((prev) => {
      const next = prev.filter((key) => validSelectionKeys.has(key));
      return sameRowSelectionKeys(prev, next) ? prev : next;
    });
  }, [
    activeTableKey,
    clientReadOnly,
    dataSource,
    rowSelectionScopeKey,
    setSelectedRowKeysForCurrentScope,
  ]);

  // 底部分页条（页码由 Pagination 控制，每页行数由 InputNumber 自定义）
  const handlePaginationBarChange = useCallback(
    (newPage: number, newPageSize?: number) => {
      restoredFromCacheRef.current = false;
      if (newPageSize !== undefined && newPageSize !== pageSize) {
        setPageSize(newPageSize);
      }
      if (newPage !== page) {
        setPage(newPage);
      }
    },
    [page, pageSize, setPage, setPageSize]
  );

  const handleCustomPageSizeChange = useCallback(
    (value: number | null) => {
      if (value == null || Number.isNaN(value)) return;
      const n = Math.min(TABLE_PAGE_SIZE_MAX, Math.max(1, Math.floor(value)));
      if (n === pageSize) return;
      restoredFromCacheRef.current = false;
      setPageSize(n);
    },
    [pageSize, setPageSize]
  );

  // 处理筛选（由 WhereFilterBuilder 构建 WHERE 子句后调用）
  const handleFilter = useCallback(
    (clause: string, rows?: WhereFilterConfig[]) => {
      restoredFromCacheRef.current = false;
      setWhereClause(clause, rows);
    },
    [setWhereClause]
  );

  // 构建当前数据查询的完整 SQL（用于展示，反映实际执行的查询）
  const currentDataSql =
    database && table
      ? (() => {
          const quoteIdentifier = (value: string) =>
            currentDatabaseType === "postgres"
              ? `"${String(value).replace(/"/g, '""')}"`
              : currentDatabaseType === "sqlserver"
                ? `[${String(value).replace(/]/g, "]]")}]`
                : `\`${String(value).replace(/`/g, "``")}\``;
          const selectPart =
            selectColumns && selectColumns.length > 0
              ? selectColumns.map((c) => quoteIdentifier(c)).join(", ")
              : "*";
          const wherePart = whereClause.trim() ? ` WHERE ${whereClause}` : "";
          const orderPart =
            sortFields.length > 0
              ? ` ORDER BY ${sortFields
                  .map((f) => `${quoteIdentifier(String(f.column))} ${f.order}`)
                  .join(", ")}`
              : "";
          const offset = (page - 1) * pageSize;
          if (currentDatabaseType === "sqlserver") {
            const sqlServerOrderPart = orderPart || " ORDER BY (SELECT 0)";
            return `SELECT ${selectPart} FROM ${quoteIdentifier(database)}.${quoteIdentifier(table)}${wherePart}${sqlServerOrderPart} OFFSET ${offset} ROWS FETCH NEXT ${pageSize} ROWS ONLY`;
          }
          return `SELECT ${selectPart} FROM ${quoteIdentifier(database)}.${quoteIdentifier(table)}${wherePart}${orderPart} LIMIT ${pageSize} OFFSET ${offset}`;
        })()
      : "";

  const handleCopyFilterSql = useCallback(async () => {
    if (!currentDataSql.trim()) {
      messageApi.warning("没有可复制的 SQL");
      return;
    }
    try {
      await copyTextWithBreadcrumb(currentDataSql, "table-data-filter-sql", {
        database: database ?? undefined,
        table: table ?? undefined,
      });
      messageApi.success("已复制 SQL");
    } catch {
      messageApi.error("复制到剪贴板失败");
    }
  }, [currentDataSql, database, table, messageApi]);

  // 插入新行
  const handleInsert = async () => {
    if (!insertAllowed) {
      messageApi.warning(insertDisabledReason || "当前不允许新增行");
      return;
    }
    try {
      const values = await insertForm.validateFields();
      // 过滤空值
      const cleanValues: Record<string, unknown> = {};
      for (const [k, v] of Object.entries(values)) {
        if (v !== undefined && v !== "") {
          cleanValues[k] = v;
        }
      }
      await insertRow(connId, database, table, cleanValues);
      messageApi.success("插入成功");
      setInsertModalOpen(false);
      insertForm.resetFields();
    } catch {
      // validation error or api error — handled by store
      if (dataError) {
        messageApi.error(dataError);
      }
    }
  };

  // 批量删除（按钮已在无主键时禁用，此处仍兜底校验，避免外部触发未授权写）
  const handleDelete = async () => {
    if (!primaryKeyColumn) {
      messageApi.warning(noPrimaryKeyDisabledReason);
      return;
    }
    const selectedKeySet = new Set(selectedRowKeys);
    const primaryKeyRows = collectSelectedPrimaryKeyRows(
      dataSource,
      primaryKeyColumns,
      selectedKeySet
    );

    if (primaryKeyRows.length === 0) return;

    await deleteRows(connId, database, table, primaryKeyRows);
    setSelectedRowKeysForCurrentScope([]);
    messageApi.success(`删除 ${primaryKeyRows.length} 行成功`);
  };

  // 关闭右键菜单
  // 获取当前选中的行 (用于复制为 INSERT)
  const getSelectedRows = useCallback((): Record<string, unknown>[] => {
    if (selectedRowKeys.length === 0) return [];
    const keySet = new Set(selectedRowKeys);
    return dataSource.filter((r) => keySet.has(String(r._selectionKey)));
  }, [selectedRowKeys, dataSource]);

  // 复制为 INSERT 语句 (基于勾选的行)
  // 当有隐藏列时，通过 queryFullRows 获取完整行数据以保证 INSERT 语句完整
  const handleCopyAsInsert = useCallback(
    async (excludePrimaryKeys: boolean) => {
      const selectedRows = getSelectedRows();
      if (selectedRows.length === 0) {
        messageApi.warning("请先勾选要复制的行");
        return;
      }

      let insertColumns: string[];
      let insertRows: Record<string, unknown>[];

      if (hiddenColumns.size > 0 && primaryKeyColumns.length > 0) {
        // 有隐藏列：按主键获取 SELECT * 完整数据
        try {
          const fullResult = await (async () => {
            if (primaryKeyColumns.length === 1) {
              const pkValues = selectedRows
                .map((r) => r[primaryKeyColumn])
                .filter((v) => v !== undefined);
              if (pkValues.length === 0) {
                messageApi.warning("无法获取选中行的主键值");
                return null;
              }
              return queryFullRows(
                connId,
                database,
                table,
                primaryKeyColumn,
                pkValues
              );
            }

            const primaryKeyRows = selectedRows
              .map((row) => getRecordPrimaryKeys(row, primaryKeyColumns))
              .filter((primaryKeys) =>
                primaryKeyColumns.every(
                  (pk) =>
                    Object.prototype.hasOwnProperty.call(primaryKeys, pk) &&
                    primaryKeys[pk] !== undefined
                )
              );
            if (primaryKeyRows.length === 0) {
              messageApi.warning("无法获取选中行的主键值");
              return null;
            }
            return queryFullRows(
              connId,
              database,
              table,
              primaryKeyColumn,
              [],
              primaryKeyRows
            );
          })();
          if (!fullResult) return;
          insertColumns = fullResult.columns;
          insertRows = fullResult.rows.map((row) => {
            const obj: Record<string, unknown> = {};
            fullResult.columns.forEach((col, i) => {
              obj[col] = row[i];
            });
            return obj;
          });
        } catch (e) {
          messageApi.error(`获取完整行数据失败: ${e}`);
          return;
        }
      } else {
        insertColumns = columns;
        insertRows = selectedRows;
      }

      const excludeCols = excludePrimaryKeys ? primaryKeyColumns : [];
      const sql = generateInsertStatements(
        table,
        insertColumns,
        insertRows,
        excludeCols
      );

      if (!sql) {
        messageApi.warning("无法生成 INSERT 语句");
        return;
      }

      try {
        await copyTextWithBreadcrumb(sql, "table-data-copy-insert", {
          database,
          table,
          row_count: insertRows.length,
          exclude_primary_keys: excludePrimaryKeys,
        });
        messageApi.success(
          `已复制 INSERT 语句${excludePrimaryKeys ? " (不含主键)" : ""}`
        );
      } catch {
        messageApi.error("复制到剪贴板失败");
      }
    },
    [
      getSelectedRows,
      table,
      columns,
      primaryKeyColumns,
      primaryKeyColumn,
      hiddenColumns,
      connId,
      database,
      messageApi,
    ]
  );

  // 复制为 JSON 数组：仅包含当前在列设置中显示的列（与表格可见列一致），值含未提交的单元格编辑
  const handleCopyAsJson = useCallback(async () => {
    const selectedRows = getSelectedRows();
    if (selectedRows.length === 0) {
      messageApi.warning("请先勾选要复制的行");
      return;
    }
    if (visibleColNames.length === 0) {
      messageApi.warning("没有可导出的列，请在列设置中至少显示一列");
      return;
    }
    const rowsWithPending = selectedRows.map((row) => {
      const merged: Record<string, unknown> = { ...row };
      const primaryKeys = getRecordPrimaryKeys(row, primaryKeyColumns);
      const hasPrimaryKeys = Object.keys(primaryKeys).length > 0;
      for (const col of visibleColNames) {
        const pending = hasPrimaryKeys
          ? pendingChanges.get(buildPendingChangeKey(primaryKeys, col))
          : undefined;
        if (pending) merged[col] = pending.newValue;
      }
      return merged;
    });
    const json = rowsToJsonArrayString(rowsWithPending, visibleColNames);
    try {
      await copyTextWithBreadcrumb(json, "table-data-copy-json", {
        database,
        table,
        row_count: rowsWithPending.length,
        column_count: visibleColNames.length,
      });
      messageApi.success("已复制 JSON 数组");
    } catch {
      messageApi.error("复制到剪贴板失败");
    }
  }, [
    database,
    getSelectedRows,
    messageApi,
    pendingChanges,
    primaryKeyColumns,
    table,
    visibleColNames,
  ]);

  const handleExportPageExcel = useCallback(async () => {
    if (!database || !table) return;
    if (visibleColNames.length === 0) {
      messageApi.warning("没有可导出的列，请在列设置中至少显示一列");
      return;
    }
    if (dataSource.length === 0) {
      messageApi.warning("当前页没有数据");
      return;
    }
    try {
      assertCsvRowWithinLimit(dataSource.length);
      const rows: unknown[][] = dataSource.map((row) => {
        const primaryKeys = getRecordPrimaryKeys(row, primaryKeyColumns);
        const hasPrimaryKeys = Object.keys(primaryKeys).length > 0;
        return visibleColNames.map((col) => {
          const pending = hasPrimaryKeys
            ? pendingChanges.get(buildPendingChangeKey(primaryKeys, col))
            : undefined;
          return pending ? pending.newValue : row[col];
        });
      });
      const safeTable = table.replace(/[^\w.-]+/g, "_");
      const b64 = await buildQueryResultWorkbookBase64(
        visibleColNames,
        rows,
        safeTable
      );
      const name = `${safeTable}_page${page}.xlsx`;
      const ok = await saveExcelWithDialog(name, b64);
      if (ok) messageApi.success("已导出当前页为 Excel");
    } catch (e) {
      messageApi.error(String(e));
    }
  }, [
    database,
    table,
    visibleColNames,
    dataSource,
    pendingChanges,
    primaryKeyColumns,
    page,
    messageApi,
  ]);

  return (
    <div style={{ display: "flex", flexDirection: "column", height: "100%" }}>
      {contextHolder}

      {/* 工具栏 */}
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: 12,
          gap: 12,
          flexWrap: "wrap",
        }}
      >
        <Space>
          <Tooltip title="刷新数据">
            <Button
              icon={<ReloadOutlined />}
              size="small"
              onClick={handleRefresh}
              loading={dataLoading}
            />
          </Tooltip>
          <Tooltip title="刷新分页（重新统计总行数，不重新加载当前页数据，Cmd/Ctrl+Shift+R）">
            <Button
              icon={<CalculatorOutlined />}
              size="small"
              aria-label="刷新分页"
              onClick={() => void handleRefreshPagination()}
              loading={totalCountLoading && !dataLoading}
            />
          </Tooltip>
          <Tooltip title="将当前页可见列导出为 Excel（含未提交的单元格编辑）">
            <Button
              icon={<FileExcelOutlined />}
              size="small"
              type="text"
              aria-label="导出本页为 Excel"
              onClick={() => void handleExportPageExcel()}
            />
          </Tooltip>
          <Popover
            trigger="click"
            title={
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                }}
              >
                <span>列显示设置</span>
                <Space size={4}>
                  <Button
                    type="link"
                    size="small"
                    onClick={() => {
                      const hadHidden = hiddenColumns.size > 0;
                      setStoreHiddenColumns(stableConnId, database, table, []);
                      if (hadHidden && connId && database && table) {
                        loadData(connId, database, table, undefined);
                      }
                    }}
                  >
                    全部显示
                  </Button>
                  <Button
                    type="link"
                    size="small"
                    onClick={() =>
                      setStoreHiddenColumns(
                        stableConnId,
                        database,
                        table,
                        allColumnNames
                      )
                    }
                  >
                    全部隐藏
                  </Button>
                </Space>
              </div>
            }
            content={
              <div style={{ width: 260 }}>
                {allColumnNames.length > 10 && (
                  <SafeInput
                    size="small"
                    placeholder="搜索列名..."
                    value={columnSearchText}
                    onChange={(e) => setColumnSearchText(e.target.value)}
                    style={{ marginBottom: 8 }}
                    allowClear
                  />
                )}
                <div style={{ maxHeight: 360, overflowY: "auto" }}>
                  {searchColumns(allColumnNames, columnSearchText).map(
                    (col) => (
                      <div key={col} style={{ padding: "2px 0" }}>
                        <Checkbox
                          checked={!hiddenColumns.has(col)}
                          onChange={() => toggleColumnVisibility(col)}
                        >
                          <Text style={{ fontSize: 12 }}>{col}</Text>
                        </Checkbox>
                      </div>
                    )
                  )}
                </div>
              </div>
            }
          >
            <Tooltip
              title={
                hiddenColumns.size > 0
                  ? `列显示设置（已显示 ${allColumnNames.length - hiddenColumns.size}/${allColumnNames.length} 列）`
                  : "列显示设置"
              }
            >
              <Button
                icon={<SettingOutlined />}
                size="small"
                type="text"
                aria-label={
                  hiddenColumns.size > 0
                    ? `列显示设置，已显示 ${allColumnNames.length - hiddenColumns.size} 列，共 ${allColumnNames.length} 列`
                    : "列显示设置"
                }
              />
            </Tooltip>
          </Popover>
          <span
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: 0,
            }}
          >
            <Tooltip
              title={
                hasActiveFilter
                  ? `筛选（已启用 ${enabledFilterCount} 条条件）`
                  : "筛选"
              }
            >
              <Badge
                className="table-data-filter-badge"
                count={hasActiveFilter ? enabledFilterCount : 0}
                size="small"
                color="var(--color-primary)"
                offset={[-6, 6]}
              >
                <span style={{ display: "inline-flex", overflow: "visible" }}>
                  <Button
                    icon={<FilterOutlined />}
                    size="small"
                    type="text"
                    aria-label="筛选"
                    onClick={() => setFilterModalOpen(true)}
                    style={{ overflow: "visible" }}
                  />
                </span>
              </Badge>
            </Tooltip>
            {whereClause?.trim() && currentDataSql ? (
              <Tooltip title="查看筛选后的查询 SQL">
                <Button
                  icon={<CodeOutlined />}
                  size="small"
                  type="text"
                  aria-label="查看筛选后的查询 SQL"
                  onClick={() => setFilterSqlPreviewOpen(true)}
                />
              </Tooltip>
            ) : null}
          </span>
          {sortFields.length > 0 ? (
            <Tooltip title="列头：单击主排序；Shift 或 ⌘+单击追加次要键。此处可调整优先级 (↑↓)、移除单列或全部清空。">
              <span
                style={{
                  display: "inline-flex",
                  alignItems: "center",
                  flexWrap: "wrap",
                  gap: 6,
                  maxWidth: 480,
                }}
              >
                <Text type="secondary" style={{ fontSize: 12, flexShrink: 0 }}>
                  排序
                </Text>
                {sortFields.map((f, idx) => (
                  <Tag
                    key={`${f.column}:${idx}`}
                    style={{
                      margin: 0,
                      display: "inline-flex",
                      alignItems: "center",
                      gap: 2,
                      fontSize: 12,
                    }}
                    closable
                    onClose={(e) => {
                      e.preventDefault();
                      restoredFromCacheRef.current = false;
                      removeSortField(f.column);
                    }}
                  >
                    <span style={{ opacity: 0.75 }}>{idx + 1}.</span>
                    <span>{f.column}</span>
                    <span>{f.order === "ASC" ? "↑" : "↓"}</span>
                    {sortFields.length > 1 ? (
                      <span
                        style={{ display: "inline-flex", marginLeft: 2 }}
                        onClick={(ev) => ev.stopPropagation()}
                      >
                        <Tooltip title="提高优先级">
                          <Button
                            type="text"
                            size="small"
                            icon={<ArrowUpOutlined style={{ fontSize: 10 }} />}
                            disabled={idx === 0}
                            aria-label={`将「${f.column}」在排序中提前`}
                            onClick={() => {
                              restoredFromCacheRef.current = false;
                              shiftSortFieldPriority(idx, -1);
                            }}
                            style={{
                              width: 20,
                              height: 20,
                              minWidth: 20,
                              padding: 0,
                            }}
                          />
                        </Tooltip>
                        <Tooltip title="降低优先级">
                          <Button
                            type="text"
                            size="small"
                            icon={
                              <ArrowDownOutlined style={{ fontSize: 10 }} />
                            }
                            disabled={idx === sortFields.length - 1}
                            aria-label={`将「${f.column}」在排序中后移`}
                            onClick={() => {
                              restoredFromCacheRef.current = false;
                              shiftSortFieldPriority(idx, 1);
                            }}
                            style={{
                              width: 20,
                              height: 20,
                              minWidth: 20,
                              padding: 0,
                            }}
                          />
                        </Tooltip>
                      </span>
                    ) : null}
                  </Tag>
                ))}
                <Button
                  size="small"
                  type="link"
                  style={{ padding: "0 4px", height: 22 }}
                  onClick={() => {
                    restoredFromCacheRef.current = false;
                    setSort(undefined, undefined);
                  }}
                >
                  清空排序
                </Button>
              </span>
            </Tooltip>
          ) : null}
          <Checkbox
            checked={showInvisibleChars}
            onChange={(e) => setShowInvisibleChars(e.target.checked)}
            style={{ fontSize: 12 }}
          >
            显示不可见字符
          </Checkbox>
          <Tooltip title={insertAllowed ? "新增行" : insertDisabledReason}>
            <Button
              icon={<PlusOutlined />}
              size="small"
              type="primary"
              aria-label="新增行"
              disabled={!insertAllowed}
              onClick={() => {
                insertForm.resetFields();
                setInsertModalOpen(true);
              }}
            />
          </Tooltip>
          {selectedRowKeys.length > 0 && (
            <>
              <Tooltip title="将勾选的行复制为 INSERT 语句">
                <Button
                  type="text"
                  icon={<ConsoleSqlOutlined />}
                  size="small"
                  aria-label="复制为 INSERT 语句"
                  onClick={() => handleCopyAsInsert(false)}
                />
              </Tooltip>
              <Tooltip title="将勾选的行按当前可见列导出为 JSON 数组并复制">
                <Button
                  type="text"
                  icon={<ApiOutlined />}
                  size="small"
                  aria-label="复制为 JSON 数组"
                  onClick={() => void handleCopyAsJson()}
                />
              </Tooltip>
              <Tooltip title="将勾选的行复制为 INSERT 语句 (不含主键列)">
                <Button
                  type="text"
                  icon={<ScissorOutlined />}
                  size="small"
                  aria-label="复制为 INSERT 语句（不含主键）"
                  onClick={() => handleCopyAsInsert(true)}
                />
              </Tooltip>
            </>
          )}
          {pendingCount > 0 && (
            <>
              <Tooltip title={rowEditDisabledReason || undefined}>
                <Badge count={pendingCount} size="small" offset={[-4, 0]}>
                  <Button
                    icon={<CheckOutlined />}
                    size="small"
                    type="primary"
                    style={{
                      backgroundColor: "#52c41a",
                      borderColor: "#52c41a",
                    }}
                    disabled={!rowOperationsAllowed}
                    onClick={() => setReviewModalOpen(true)}
                  >
                    提交修改
                  </Button>
                </Badge>
              </Tooltip>
              <Tooltip title="撤销全部待提交修改">
                <Button
                  icon={<UndoOutlined />}
                  size="small"
                  onClick={handleDiscardAll}
                >
                  撤销全部
                </Button>
              </Tooltip>
            </>
          )}
          {capabilities.tableDataEditing &&
            selectedRowKeys.length > 0 &&
            (rowOperationsAllowed ? (
              <Popconfirm
                title={`确定删除选中的 ${selectedRowKeys.length} 行?`}
                onConfirm={handleDelete}
                okText="删除"
                cancelText="取消"
                okButtonProps={{ danger: true }}
              >
                <Button
                  icon={<DeleteOutlined />}
                  size="small"
                  danger
                  aria-label={`删除选中的 ${selectedRowKeys.length} 行`}
                >
                  {selectedRowKeys.length}
                </Button>
              </Popconfirm>
            ) : (
              <Tooltip
                title={rowEditDisabledReason || noPrimaryKeyDisabledReason}
              >
                {/* Tooltip 需要可聚焦的子元素来承载 disabled 状态 */}
                <span>
                  <Button
                    icon={<DeleteOutlined />}
                    size="small"
                    danger
                    disabled
                    aria-label={`删除选中的 ${selectedRowKeys.length} 行（禁用）`}
                  >
                    {selectedRowKeys.length}
                  </Button>
                </span>
              </Tooltip>
            ))}
        </Space>

        {/* 筛选入口已移动到工具栏右侧的筛选图标按钮 */}
      </div>

      {/* 筛选弹窗：编辑筛选条件，点击“保存并应用”后才真正应用筛选 */}
      <Modal
        title="筛选"
        open={filterModalOpen}
        onCancel={() => setFilterModalOpen(false)}
        footer={null}
        width={760}
        destroyOnHidden
      >
        <WhereFilterBuilder
          key={`${connId}-${database}-${table}-${filterModalOpen ? "open" : "closed"}`}
          columns={tableStructure?.map((c) => c.name) ?? columns}
          columnTypes={
            tableStructure
              ? Object.fromEntries(
                  tableStructure.map((c) => [c.name, c.column_type])
                )
              : undefined
          }
          databaseType={currentDatabaseType}
          initialFilterRows={filterRows}
          primaryButtonText="保存并应用"
          clearButtonText="清空筛选"
          onFilter={(clause, rows) => {
            handleFilter(clause, rows);
            setFilterModalOpen(false);
          }}
          onClear={() => {
            setWhereClause("", []);
            setFilterModalOpen(false);
          }}
        />
      </Modal>

      <Modal
        title="筛选后的查询 SQL"
        open={filterSqlPreviewOpen}
        onCancel={() => setFilterSqlPreviewOpen(false)}
        destroyOnHidden
        width={720}
        footer={
          <Space>
            <Button onClick={() => setFilterSqlPreviewOpen(false)}>关闭</Button>
            <Button type="primary" onClick={() => void handleCopyFilterSql()}>
              复制 SQL
            </Button>
          </Space>
        }
      >
        <pre
          style={{
            margin: 0,
            padding: 12,
            fontSize: 12,
            fontFamily: "monospace",
            whiteSpace: "pre-wrap",
            wordBreak: "break-all",
            backgroundColor: "var(--bg-elevated)",
            borderRadius: 6,
            maxHeight: "min(50vh, 360px)",
            overflow: "auto",
          }}
        >
          {currentDataSql}
        </pre>
      </Modal>

      {/* 错误提示 */}
      {dataError && (
        <Alert
          type="error"
          message="操作失败"
          description={dataError}
          showIcon
          closable
          style={{ marginBottom: 12 }}
        />
      )}

      {/* 数据表格 slot：垂直 flex 容器，把"表格区 + resize bar"包成一个可调节高度的整体。
          - 自动模式（userTableHeight === null）：表格 flex:1 撑满 slot 剩余空间。
          - 手动模式：表格固定高度 = userTableHeight，多余空间作为 resize bar 之下的留白。 */}
      <div
        className="table-data-slot"
        style={{
          flex: 1,
          display: "flex",
          flexDirection: "column",
          minHeight: 0,
          overflow: "hidden",
        }}
        ref={tableSlotRef}
      >
        {/* 表格容器：基于 @tanstack/react-virtual 的行+列双向虚拟化实现，
            通过原生 scrollLeft 驱动列窗口更新，不再依赖 antd 内部 scroll 事件钩子。 */}
        <div
          ref={tableContainerRef}
          className="table-data-container"
          style={
            userTableHeight == null
              ? { flex: 1, overflow: "hidden", minHeight: TABLE_HEIGHT_MIN }
              : {
                  flex: "0 0 auto",
                  height: effectiveTableHeight,
                  overflow: "hidden",
                  minHeight: TABLE_HEIGHT_MIN,
                }
          }
        >
          <VirtualDataTable
            key={tableKey || "no-table"}
            columns={tableColumns}
            dataSource={dataSource}
            rowKey={vdtRowKey}
            loading={dataLoading}
            height={effectiveTableHeight}
            defaultColWidth={DEFAULT_COL_WIDTH}
            testId={
              database && table ? `table-vdt-${database}-${table}` : "table-vdt"
            }
            rowSelection={vdtRowSelection}
            renderRevision={pendingChanges}
          />
        </div>
        {/* 高度调节条：拖拽改变表格高度，双击重置为自动撑满模式 */}
        <div
          className={`table-data-resize-bar${isResizing ? " is-active" : ""}`}
          role="separator"
          aria-orientation="horizontal"
          aria-label="拖动调整表格高度，双击重置"
          title={
            userTableHeight == null
              ? "拖动调整表格高度（双击重置为自动撑满）"
              : `当前高度 ${userTableHeight}px - 拖动调整，双击重置为自动撑满`
          }
          onMouseDown={handleResizeStart}
          onDoubleClick={handleResizeReset}
        />
        {/* 用户手动缩小表格后剩余的留白由这个 spacer 吃掉，避免分页栏被吸到表格底部 */}
        {userTableHeight != null && <div style={{ flex: 1, minHeight: 0 }} />}
      </div>

      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          flexWrap: "wrap",
          gap: 12,
          paddingTop: 8,
        }}
      >
        <div style={{ flex: 1, minWidth: 0 }}>
          {totalCountStale && !totalCountLoading && (
            <Text type="warning" style={{ fontSize: 12 }}>
              总数可能已变化，点击刷新分页更新
            </Text>
          )}
        </div>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            flexWrap: "wrap",
            gap: 12,
          }}
        >
          <Space size={4} align="center">
            <Text type="secondary" style={{ fontSize: 12 }}>
              每页
            </Text>
            <InputNumber
              min={1}
              max={TABLE_PAGE_SIZE_MAX}
              precision={0}
              size="small"
              value={pageSize}
              aria-label="每页行数"
              style={{ width: 88 }}
              onChange={handleCustomPageSizeChange}
            />
            <Text type="secondary" style={{ fontSize: 12 }}>
              条
            </Text>
          </Space>
          <Pagination
            size="small"
            current={page}
            pageSize={pageSize}
            total={total}
            showQuickJumper
            showSizeChanger={false}
            showTotal={() =>
              totalCountLoading
                ? "正在统计行数…"
                : `共 ${total.toLocaleString()} 行`
            }
            onChange={handlePaginationBarChange}
          />
        </div>
      </div>

      {/* 状态栏 */}
      {executionTime !== null && (
        <div
          style={{
            padding: "4px 0",
            fontSize: 11,
            color: "var(--text-secondary)",
            display: "flex",
            gap: 16,
          }}
        >
          <span>
            <ClockCircleOutlined style={{ marginRight: 4 }} />
            {executionTime}ms
          </span>
          <span>
            第 {page} 页
            {!totalCountLoading && ` / 共 ${Math.ceil(total / pageSize)} 页`}
          </span>
        </div>
      )}

      {/* 新增行 Modal */}
      <Modal
        title="新增行"
        open={insertModalOpen}
        onOk={handleInsert}
        onCancel={() => setInsertModalOpen(false)}
        okText="插入"
        cancelText="取消"
        width={640}
        styles={{
          content: {
            display: "flex",
            flexDirection: "column",
            height: "calc(100vh - 48px)",
            maxHeight: 720,
          },
          body: {
            flex: "1 1 auto",
            minHeight: 0,
            overflowY: "auto",
          },
        }}
        destroyOnHidden
      >
        <Form form={insertForm} layout="vertical" size="small">
          {tableStructure?.map((col) => {
            const autoTag = describeAutoGeneratedColumn(col.extra);
            const isAutoGenerated = autoTag != null;
            return (
              <Form.Item
                key={col.name}
                name={col.name}
                label={
                  <Space size={4}>
                    <span>{col.name}</span>
                    <Text type="secondary" style={{ fontSize: 11 }}>
                      {col.column_type}
                    </Text>
                    {autoTag && (
                      <Text type="secondary" style={{ fontSize: 10 }}>
                        ({autoTag})
                      </Text>
                    )}
                  </Space>
                }
                rules={
                  !col.nullable &&
                  col.default_value === null &&
                  !isAutoGenerated
                    ? [{ required: true, message: `${col.name} 不能为空` }]
                    : undefined
                }
              >
                <SafeInput
                  placeholder={
                    isAutoGenerated
                      ? "自动生成, 留空即可"
                      : col.nullable
                        ? "可选 (NULL)"
                        : `请输入 ${col.name}`
                  }
                />
              </Form.Item>
            );
          })}
        </Form>
      </Modal>

      {/* 提交修改确认 Modal */}
      <Modal
        title={`确认提交修改 (${pendingCount} 项)`}
        open={reviewModalOpen}
        onOk={handleSubmitAll}
        onCancel={() => setReviewModalOpen(false)}
        confirmLoading={submitLoading}
        okText="全部提交"
        cancelText="取消"
        width={720}
        destroyOnHidden={false}
      >
        {pendingCount === 0 ? (
          <Alert type="info" message="没有待提交的修改" showIcon />
        ) : (
          <>
            <Table
              dataSource={Array.from(pendingChanges.entries()).map(
                ([key, change]) => ({ key, ...change })
              )}
              rowKey="key"
              size="small"
              pagination={false}
              scroll={{ y: 400 }}
              columns={[
                {
                  title: "行标识",
                  dataIndex: "primaryKeys",
                  key: "pk",
                  width: 140,
                  render: (pks: Record<string, unknown>) => (
                    <Text style={{ fontSize: 11 }}>
                      {Object.entries(pks)
                        .map(([k, v]) => `${k}=${v}`)
                        .join(", ")}
                    </Text>
                  ),
                },
                {
                  title: "列名",
                  dataIndex: "colName",
                  key: "colName",
                  width: 120,
                  render: (name: string) => <Text code>{name}</Text>,
                },
                {
                  title: "原始值",
                  dataIndex: "oldValue",
                  key: "oldValue",
                  width: 130,
                  render: (v: unknown) => (
                    <Text type="secondary" style={{ fontSize: 12 }}>
                      {showInvisibleChars && typeof v === "string"
                        ? visualizeInvisibleChars(displayVal(v))
                        : displayVal(v)}
                    </Text>
                  ),
                },
                {
                  title: "新值",
                  key: "newValue",
                  width: 160,
                  render: (
                    _: unknown,
                    record: PendingChange & { key: string }
                  ) => (
                    <SafeInput
                      size="small"
                      value={
                        record.newValue === null ? "" : String(record.newValue)
                      }
                      onChange={(e) => {
                        const raw = e.target.value;
                        const val = normalizeValue(raw, record.oldValue, {
                          forceString: isStringColumnType(
                            columnTypesByName[record.colName] ?? ""
                          ),
                        });
                        handleUpdatePendingValue(record.key, val);
                      }}
                      style={{ fontSize: 12 }}
                    />
                  ),
                },
                {
                  title: "",
                  key: "action",
                  width: 50,
                  render: (_: unknown, record: { key: string }) => (
                    <Tooltip title="移除此项修改">
                      <Button
                        type="link"
                        size="small"
                        danger
                        icon={<DeleteOutlined />}
                        onClick={() => handleRemovePending(record.key)}
                        style={{ padding: 0, minWidth: 0 }}
                      />
                    </Tooltip>
                  ),
                },
              ]}
            />
            <div style={{ marginTop: 16 }}>
              <Text
                type="secondary"
                style={{ fontSize: 12, display: "block", marginBottom: 4 }}
              >
                即将执行的 SQL：
              </Text>
              <pre
                style={{
                  margin: 0,
                  padding: 12,
                  background: "var(--bg-secondary)",
                  borderRadius: 4,
                  fontSize: 12,
                  maxHeight: 120,
                  overflow: "auto",
                  whiteSpace: "pre-wrap",
                  wordBreak: "break-all",
                }}
              >
                <code>
                  {generateUpdateStatements(
                    database,
                    table,
                    Array.from(pendingChanges.values()).filter(
                      (c) => Object.keys(c.primaryKeys).length > 0
                    )
                  )}
                </code>
              </pre>
            </div>
          </>
        )}
      </Modal>
    </div>
  );
}
